# Nombre de tu aplicación backend
spring.application.name=backend

# ===============================
# DATABASE (POSTGRES - NEON)
# ===============================
# spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_local}
# spring.datasource.username=${DB_USER:postgres}
# spring.datasource.password=${DB_PASSWORD:password}

# 1. URL de la base de datos (localhost porque está en tu máquina, puerto 5433 y el nombre de tu BD)
spring.datasource.url=jdbc:postgresql://localhost:5433/tracking_web

# 2. Credenciales de acceso
spring.datasource.username=postgres
spring.datasource.password=base123

# 3. Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver



# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}


# Nivel general
logging.level.root=INFO

# 👇 ver tus clases específicas (el más útil)
logging.level.com.tracking.backend=DEBUG

# Ver el SQL que ejecuta Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE  
# ver los valores de los parámetros

# Ver qué requests llegan y qué responde Spring
logging.level.org.springframework.web=DEBUG